public class SchemaFieldsCntrl {

    public String lstPickvals { get; set; }

    public PageReference PickListValues() {
        return null;
    }


    public String SelPicklist { get; set; }

    public String SelObjPicklists { get; set; }

    public PageReference FieldNames() {
        return null;
    }


    public String getOptions() {
        return null;
    }


    public String selected { get; set; }
}